"use client";

import { type FormEvent, useEffect, useState } from "react";

const SUPABASE_URL = process.env.NEXT_PUBLIC_SUPABASE_URL ?? "";
const SUPABASE_ANON_KEY = process.env.NEXT_PUBLIC_SUPABASE_ANON_KEY ?? "";

interface DesktopFlow {
  /** PKCE code challenge generated by the desktop app. */
  cc: string;
  /** CSRF/correlation token echoed back to the desktop via the callback. */
  state: string;
}

export default function LoginPage() {
  // undefined = still reading the URL; null = launched outside the desktop flow.
  const [flow, setFlow] = useState<DesktopFlow | null | undefined>(undefined);
  const [email, setEmail] = useState("");
  const [sending, setSending] = useState(false);
  const [message, setMessage] = useState<string | null>(null);

  useEffect(() => {
    const params = new URLSearchParams(window.location.search);
    const cc = params.get("cc");
    const state = params.get("state");
    setFlow(cc && state ? { cc, state } : null);
  }, []);

  if (!SUPABASE_URL || !SUPABASE_ANON_KEY) {
    return (
      <main>
        <h1>MeetCopilot</h1>
        <p>
          Auth is not configured. Set <code>NEXT_PUBLIC_SUPABASE_URL</code> and{" "}
          <code>NEXT_PUBLIC_SUPABASE_ANON_KEY</code>.
        </p>
      </main>
    );
  }

  if (flow === undefined) {
    return (
      <main>
        <p>Loading…</p>
      </main>
    );
  }

  if (flow === null) {
    return (
      <main>
        <h1>Sign in to MeetCopilot</h1>
        <p>Please start sign-in from the MeetCopilot desktop app.</p>
      </main>
    );
  }

  const { cc, state } = flow;
  const redirectTo = `${window.location.origin}/auth/callback?state=${encodeURIComponent(state)}`;

  function signInWithGoogle() {
    const url = new URL(`${SUPABASE_URL}/auth/v1/authorize`);
    url.searchParams.set("provider", "google");
    url.searchParams.set("code_challenge", cc);
    url.searchParams.set("code_challenge_method", "s256");
    url.searchParams.set("redirect_to", redirectTo);
    window.location.href = url.toString();
  }

  async function sendMagicLink(event: FormEvent<HTMLFormElement>) {
    event.preventDefault();
    setSending(true);
    setMessage(null);
    try {
      const res = await fetch(
        `${SUPABASE_URL}/auth/v1/otp?redirect_to=${encodeURIComponent(redirectTo)}`,
        {
          method: "POST",
          headers: { apikey: SUPABASE_ANON_KEY, "Content-Type": "application/json" },
          body: JSON.stringify({
            email,
            create_user: true,
            code_challenge: cc,
            code_challenge_method: "s256",
          }),
        },
      );
      if (!res.ok) {
        setMessage(`Could not send the link: ${await res.text()}`);
      } else {
        setMessage(`Check ${email} for a sign-in link, then return to this tab.`);
      }
    } catch (err) {
      setMessage(`Network error: ${err instanceof Error ? err.message : String(err)}`);
    } finally {
      setSending(false);
    }
  }

  return (
    <main>
      <h1>Sign in to MeetCopilot</h1>
      <button type="button" className="btn btn-primary" onClick={signInWithGoogle}>
        Continue with Google
      </button>

      <div className="divider">or</div>

      <form onSubmit={sendMagicLink} className="form">
        <label htmlFor="email">Email</label>
        <input
          id="email"
          type="email"
          required
          value={email}
          onChange={(e) => setEmail(e.target.value)}
          placeholder="you@example.com"
        />
        <button type="submit" className="btn" disabled={sending}>
          {sending ? "Sending…" : "Send magic link"}
        </button>
      </form>

      {message && <p className="message">{message}</p>}
    </main>
  );
}
